# Generated by Django 5.2.3 on 2025-06-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='邮箱地址')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='订阅时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('confirmation_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='确认令牌')),
                ('confirmed', models.BooleanField(default=False, verbose_name='是否已确认')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='最后发送时间')),
                ('unsubscribe_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='退订令牌')),
            ],
            options={
                'verbose_name': '邮件订阅者',
                'verbose_name_plural': '邮件订阅者',
                'db_table': 'EmailSubscribers',
                'indexes': [models.Index(fields=['email'], name='EmailSubscri_email_6284a6_idx'), models.Index(fields=['is_active'], name='EmailSubscri_is_acti_1f6cac_idx')],
            },
        ),
    ]
