# Generated by Django 5.2.3 on 2025-06-29 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0002_auto_20250629_1355'),
    ]

    operations = [
        # 删除所有重命名索引的操作
    ]
