# Generated by Django 5.2.3 on 2025-06-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentinel', '0003_rename_emailsubscri_email_6284a6_idx_emailsubscr_email_ba6310_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS EmailSubscribers (
                id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
                email VARCHAR(100) NOT NULL,
                name VARCHAR(50),
                subscribed_at DATETIME NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                confirmation_token VARCHAR(100),
                confirmed BOOLEAN NOT NULL DEFAULT FALSE,
                last_sent_at DATETIME,
                unsubscribe_token VARCHAR(100),
                UNIQUE KEY (email),
                INDEX EmailSubscr_email_ba6310_idx (email),
                INDEX EmailSubscr_is_acti_a83fb4_idx (is_active)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
            """,
            """
            DROP TABLE IF EXISTS EmailSubscribers;
            """
        ),
    ]
